"""
Explanation module for the SpeedLimit System.

This module defines the Explanation dataclass which holds human-readable
explanations for speed decisions. These explanations are used for user
interfaces, logging, and system transparency, helping users understand why
a particular speed limit was chosen.
"""

from dataclasses import dataclass


@dataclass
class Explanation:
    """
    Represents a human-readable explanation for a speed decision.
    
    Contains a text description that explains the reasoning behind a speed
    limit decision. This explanation is generated by the SpeedLimitSystem
    to provide transparency and help users understand the system's behavior.
    
    Attributes:
        text: Human-readable explanation text describing the decision
    """
    
    text: str
    
    def __str__(self) -> str:
        """
        Returns the explanation text as a string.
        
        This method allows the Explanation object to be used directly in
        string contexts (e.g., print statements, logging, UI display).
        
        Returns:
            The explanation text string
        """
        return self.text

